language: python

python:
  - 2.7
  - 3.6

install:
  - pip install -r requirements-dev.txt
  - pip install codecov

script:
  - py.test --pep8 tea --cov tea

after_success:
  - codecov

deploy:
  provider: pypi
  user: alefnula
  password:
    secure: IZ0nvhdhxxDPGUnCdMdzW72zSldZW5wWnSlwmXgBwQNdoTM0zgDnPk9uC0srixPkctovtUFLZxvshUDdSBwBiFjzuFGb2vhDAzUN6cRrWEion9A368Liu0ujytsb8jEnWUmafLOpPF4EJzhlINi+uy1gqb+HZ/DpTZc/LeajtFQ=
  on:
    tags: true
    branch: master
    distributions: sdist bdist_wheel
    repo: alefnula/tea
